name: CI/CD Pipeline for Simple App

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  # Job 1: Build and Test (Continuous Integration part)
  build-and-test:
    runs-on: ubuntu-latest # Use a virtual machine with Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Get your repository code

      - name: Setup Node.js (for running test.js)
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify Node.js version

      - name: Run simple test
        run: node test.js # Execute your test script

  # Job 2: Deploy (Continuous Deployment part)
  deploy:
    needs: build-and-test # This job only runs if 'build-and-test' job succeeds
    runs-on: ubuntu-latest # Use a virtual machine with Ubuntu
    environment:
      name: github-pages # Use the predefined GitHub Pages environment
      url: ${{ steps.deployment.outputs.page_url }} # The URL where the app will be deployed

    permissions: # Permissions needed for GitHub Pages deployment
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Get your repository code again

      - name: Setup Pages
        uses: actions/configure-pages@v5 # Configure GitHub Pages environment

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Upload all files in the current directory (your index.html)

      - name: Deploy to GitHub Pages
        id: deployment # Give this step an ID to reference its outputs
        uses: actions/deploy-pages@v4 # Perform the deployment