name: CI/CD Pipeline for Simple App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch depth 0 ensures full history for accurate SonarCloud analysis (important for "new code" metrics)
          fetch-depth: 0

      - name: Setup Node.js (for running test.js)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run simple test # Your existing test
        run: node test.js

      # --- NEW SONARCLOUD SCAN STEP ---
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0 # Use the official SonarCloud action
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Reference the secret
        with:
          projectBaseDir: '.' # Keep this as it's a valid input
          # IMPORTANT: Replace with your actual organization and project keys
          args: >
            -organization: https://sonarcloud.io/organizations/rafy110/projects
            -projectKey: Rafy110_my-cicd-app
          # Additional parameters (optional, based on your needs)
          # You can specify the analysis scope (e.g., which directories to scan)
          # For HTML/JS, it often picks up everything by default, but you could explicitly:
          # projectBaseDir: '.' # Scan from the root of the repository
          # sources: 'index.html,test.js,.github/workflows/ci-cd-pipeline.yml' # Or specify files/dirs
          # exclusions: 'node_modules/**' # Exclude directories if they appear later
          # projectName: 'My Simple App' # Optional: A friendly name in SonarCloud
      # --- END NEW SONARCLOUD SCAN STEP ---

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4